{% set name = "physical_validation" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shirtsgroup/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c0579adeb0c506d23b4139efccfd835f3a8a5e44177ebb4a58f034d9407a967d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.7
    - pip
  run:
    - python >3.7
    - numpy
    - scipy
    - matplotlib-base
    - pymbar >=3,<5

test:
  imports:
    - physical_validation
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/shirtsgroup/physical_validation
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Physical validation of molecular simulations
  description: |
    physical_validation is a package aimed at testing results obtained by molecular dynamics
    simulations for their physical validity.
  doc_url: http://physical-validation.readthedocs.io/
  dev_url: https://github.com/shirtsgroup/physical_validation

extra:
  recipe-maintainers:
    - mattwthompson
    - ptmerz
