{% set name = "physical_validation" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shirtsgroup/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d8bd8199c0e44fc4b79d61d81a1a9964c4c0adf0879c2265a9ab19061cd97d1b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >3.6
    - pip
  run:
    - python >3.6
    - numpy
    - scipy
    - matplotlib-base
    - pymbar

test:
  imports:
    - physical_validation
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/shirtsgroup/physical_validation
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Physical validation of molecular simulations
  description: |
    physical_validation is a package aimed at testing results obtained by molecular dynamics
    simulations for their physical validity.
  doc_url: http://physical-validation.readthedocs.io/
  dev_url: https://github.com/shirtsgroup/physical_validation

extra:
  recipe-maintainers:
    - mattwthompson
    - ptmerz
